# .terrascan.yaml

# Specify the root directory for scanning
root: /workspace

# Define IaC scanning configurations
iac:
  # Exclude specific directories or file patterns
  exclude_paths:
    - "**/*.arm"             # Exclude ARM template files
    - "**/Dockerfile"        # Exclude Dockerfile
    - "**/*.yaml"            # Exclude Kubernetes YAML files
    - "**/*.yml"             # Exclude Kubernetes YAML files (alternative pattern)
    - "**/kustomization.yaml" # Exclude Kustomize configuration file
    - "**/*.helm"            # Exclude Helm charts

# Define policies to enforce (optional, specify only if needed)
policies:
  enforcement_level: "medium"
  path: "./policies"
