name: Backend Build and Push

on:
  push:
    branches: [ master ] 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' 

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Get commit hash
      id: get-commit-hash
      run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"

    - name: Build Docker image
      run: docker build -t https://058264547261.dkr.ecr.us-east-1.amazonaws.com/node-mongodb-deploy-backend:${{ steps.get-commit-hash.outputs.commit-hash }} .
      working-directory: ./backend

    - name: Push Docker image to ECR
      run: docker push https://058264547261.dkr.ecr.us-east-1.amazonaws.com/node-mongodb-deploy-backend:${{ steps.get-commit-hash.outputs.commit-hash }}
